#ifndef CONSTANT_H
#define CONSTANT_H

#define DEFAULT_SAMPLE_RATE 16000

#define DEFAULT_MIN_FREQ 32

#define DEFAULT_MAX_FREQ (DEFAULT_SAMPLE_RATE / 2)

#define DEFAULT_BINS_PER_OCTAVE 12

#define DEFAULT_HOP_SIZE 0.04

#endif // CONSTANT_H